### ISSUE TITLE
Backup Issue in S3 bucket

### ISSUE THREAD

**Issue by JJSWAIN2018** [oracle/mysql-operator#212] opened 2018-08-28 13:16 UTC
## Backup Issue in S3 bucket 

Choose one: BUG REPORT 
Backup Issue in S3 bucket

## Versions

**MySQL Operator Version**: 0.2.0

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.11
- **Cloud provider or hardware configuration**: GCP
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
When we take backup in both on-demand as well as schedule backup . multiple database .sql.gz files 
are stored in S3 bucket .
Name    Size    Type    Storage class    Last modified    Private  access     Encryption     
 db-cluster-db-backup.20180827153653.sql.gz    891.6 KB    —    Regional    8/27/18, 9:06 PM    
    
db-cluster-db-backup.20180827153654.sql.gz    891.6 KB    —    Regional    8/27/18, 9:06 PM    
  
db-cluster-db-backup.20180827153656.sql.gz    891.6 KB    —    Regional    8/27/18, 9:06 PM    
  

## What you expected to happen?
Only one backup file should be stored in s3 bucket in on-demand backup .

**Comment by Simon-Li** [comment] 2018-08-28 15:27
see this too, may look into it when have a chance.

**Comment by prydie** [comment] 2018-08-28 16:39
Thanks for the bug report @JJSWAIN2018.

I believe the issue is that the agent backup and restore controllers only check if the backup/restore is scheduled before processing rather than also checking the `v1alpha1.{Backup,Restore}Complete` condition too.

https://github.com/oracle/mysql-operator/blob/ee732cf526e71e79bfd1611bccdedc139178c10a/pkg/controllers/backup/agent_controller.go#L128-L143

https://github.com/oracle/mysql-operator/blob/ee732cf526e71e79bfd1611bccdedc139178c10a/pkg/controllers/restore/agent_controller.go#L138-L152

**Comment by prydie** [comment] 2018-08-31 12:58
Resolved by #213

**Closed by prydie** 2018-08-31 12:58 UTC
Labels: bug
